/* Dependency-free client. Every booking value is returned by the live API. */
(() => {
  'use strict';
  const API = (window.SKYLINE_API || '/api/v1').replace(/\/$/, '');
  const $ = (selector, root = document) => root.querySelector(selector);
  const state = { flights: [], itinerary: null, reservation: null, busy: false, countdown: null, demoContext: null };
  const logic = window.SkylineLogic;
  const demo = window.SKYLINE_DEMO || {};
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const unpack = body => Array.isArray(body) ? body : (body?.items || body?.results || body?.itineraries || body?.data || []);
  const reservationOf = body => body?.reservation || body;
  function notice(message, type = '') { const n = $('#notice'); n.textContent = message; n.className = `notice ${type}`; n.hidden = !message; }
  function step(name) { document.querySelectorAll('.steps span').forEach(x => x.classList.toggle('active', x.dataset.step === name)); }
  function show(id) { ['search-panel','results','passenger-panel','payment-panel','confirmation'].forEach(x => { $(`#${x}`).hidden = x !== id; }); }
  function setBusy(form, busy, text) { state.busy = busy; form.setAttribute('aria-busy', String(busy)); form.querySelectorAll('button[type="submit"]').forEach(button => { if (busy) button.dataset.label = button.textContent; button.disabled = busy; button.textContent = busy ? text : (button.dataset.label || button.textContent); }); }
  async function request(path, options = {}) { const context = state.demoContext || demo; const demoHeaders = context.role ? { 'X-Demo-Actor-Id': context.actorId || '', 'X-Demo-Role': context.role, ...(context.agencyId ? { 'X-Demo-Agency-Id': context.agencyId } : {}) } : {}; const response = await fetch(API + path, { ...options, headers: { Accept:'application/json', ...demoHeaders, ...(options.body ? {'Content-Type':'application/json'} : {}), ...(options.headers || {}) } }); let body = null; try { body = await response.json(); } catch (_) {} if (!response.ok) { const detail = body?.error || body?.detail || body; const code = detail?.code || `HTTP_${response.status}`; const message = detail?.message || (Array.isArray(detail) ? 'Check the highlighted fields.' : `Request failed (${response.status}).`); const error = new Error(message); error.code = code; error.correlationId = detail?.correlation_id; throw error; } return body; }
  function report(error) { notice(`${error.message}${error.code ? ` [${error.code}]` : ''}${error.correlationId ? ` · correlation ${error.correlationId}` : ''}`, 'error'); }
  function segment(s) { return `${esc(s.origin?.iata || s.origin || s.departure_airport || '')} → ${esc(s.destination?.iata || s.destination || s.arrival_airport || '')}`; }
  function schedule(s) { const dep = s.departure_local || s.departure_at, arr = s.arrival_local || s.arrival_at; const zone = s.timezone || s.origin_timezone || s.departure_timezone || ''; return `<div class="flight-time">${segment(s)}</div><div class="flight-meta">Depart ${esc(dep || '—')} · Arrive ${esc(arr || '—')}${zone ? ` · ${esc(zone)}` : ''}</div>`; }
  function renderFlights(body) { const flights = unpack(body); state.flights = flights; const list = $('#flight-list'); if (!flights.length) { list.innerHTML = '<p class="flight-meta">No itineraries found for these criteria.</p>'; return; } list.innerHTML = flights.map((flight, index) => { const segments = flight.segments || flight.legs || []; return `<article class="flight"><div class="flight-main">${segments.length ? segments.map(schedule).join('') : schedule(flight)}<div class="flight-meta">${segments.length} segment${segments.length === 1 ? '' : 's'} · ${esc(flight.available ?? 'Availability confirmed')}</div></div><div class="flight-price">${esc(flight.total ?? flight.price ?? '—')} <small>${esc(flight.currency || 'COP')}</small></div><button class="primary choose" type="button" data-index="${index}">Select <span aria-hidden="true">→</span></button></article>`; }).join(''); list.querySelectorAll('.choose').forEach(button => { button.onclick = () => selectFlight(flights[Number(button.dataset.index)]); }); }
  async function search(event) { event.preventDefault(); const form = event.target; if (state.busy) return; setBusy(form, true, 'Searching…'); notice('Searching live availability…'); const values = new FormData(form); if (!values.get('max_price')) values.delete('max_price'); const params = new URLSearchParams(values); params.set('origin', String(values.get('origin')).toUpperCase()); params.set('destination', String(values.get('destination')).toUpperCase()); try { renderFlights(await request(`/flights/search?${params}`)); show('results'); step('passengers'); notice(''); } catch (error) { report(error); } finally { setBusy(form, false); } }
  function selectFlight(flight) { state.itinerary = flight; const count = Number($('#search-form [name="passengers"]').value); $('#passenger-count').textContent = `${count} passenger${count === 1 ? '' : 's'}`; $('#passenger-fields').innerHTML = Array.from({ length: count }, (_, i) => `<div class="passenger"><label for="given-${i}">Given name<input id="given-${i}" name="passengers[${i}].given_name" required maxlength="100" autocomplete="given-name"></label><label for="surname-${i}">Surname<input id="surname-${i}" name="passengers[${i}].surname" required maxlength="100" autocomplete="family-name"></label></div>`).join(''); show('passenger-panel'); step('passengers'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function payload(form) { return logic.buildPayload(state.itinerary, $('#search-form [name="cabin"]').value, new FormData(form)); }
  async function createBooking(event) { event.preventDefault(); const form = event.target; if (state.busy) return; setBusy(form, true, 'Holding…'); notice('Holding seats…'); const booking = payload(form); const headers = { 'Idempotency-Key': crypto.randomUUID() }; state.demoContext = null; if (booking.channel === 'AGENCY') { state.demoContext = { role:'AGENCY_AGENT', actorId:booking.agent_id || 'agent-7', agencyId:booking.agency_id || 'agency-1' }; headers['X-Demo-Role'] = state.demoContext.role; headers['X-Demo-Actor-Id'] = state.demoContext.actorId; headers['X-Demo-Agency-Id'] = state.demoContext.agencyId; } try { state.reservation = reservationOf(await request('/reservations', { method:'POST', headers, body:JSON.stringify(booking) })); renderHold(); show('payment-panel'); step('payment'); notice('Seats held. Complete payment before the expiry time.', 'success'); } catch (error) { report(error); } finally { setBusy(form, false); } }
  function stopCountdown() { if (state.countdown) clearInterval(state.countdown); state.countdown = null; }
  function startCountdown(expiresAt) { stopCountdown(); const target = Date.parse(expiresAt); const output = $('#hold-countdown'), payButton = $('#payment-form button[type="submit"]'); payButton.disabled = false; output.removeAttribute('aria-label'); if (!Number.isFinite(target)) { output.textContent = 'Retention expiry: unavailable'; return; } const tick = () => { const seconds = Math.max(0, Math.ceil((target - Date.now()) / 1000)); output.textContent = logic.countdownText(seconds); if (!seconds) { payButton.disabled = true; output.setAttribute('aria-label', 'Retention expired; payment disabled'); stopCountdown(); } }; tick(); state.countdown = setInterval(tick, 1000); }
  function renderHold() { const r = state.reservation; $('#hold-summary').innerHTML = `<div class="detail-grid"><div>Reference<b>${esc(r.locator || r.id)}</b></div><div>Status<b>${esc(r.state || r.status)}</b></div><div>Total<b>${esc(r.total ?? '—')} ${esc(r.currency || 'COP')}</b></div><div>Expires<b>${esc(r.expires_at || '—')}</b></div></div>`; startCountdown(r.expires_at); }
  async function pay(event) { event.preventDefault(); const form = event.target; if (state.busy) return; setBusy(form, true, 'Processing…'); notice('Processing simulated payment…'); const r = state.reservation; try { const result = await request(`/reservations/${encodeURIComponent(r.id)}/payments`, { method:'POST', body:JSON.stringify({ approved: form.approved.value === 'true', operation_reference: form.operation_ref.value }) }); stopCountdown(); state.reservation = { ...r, ...result, state: result.state === 'APPROVED' ? 'CONFIRMED' : 'PAYMENT_FAILED' }; if (result.state === 'APPROVED') { state.reservation.tickets = await request(`/reservations/${encodeURIComponent(r.id)}/tickets`); } renderConfirmation(); show('confirmation'); step('manage'); notice('Payment response received.', 'success'); } catch (error) { report(error); } finally { setBusy(form, false); } }
  function renderConfirmation() { const r = state.reservation, tickets = r.tickets || []; $('#confirmation').innerHTML = `<p class="eyebrow">BOOKING RESULT</p><h2>${esc(r.state || r.status)}</h2><div class="detail-grid"><div>Reference<b>${esc(r.locator || r.id)}</b></div><div>Total<b>${esc(r.total ?? r.amount ?? '—')} ${esc(r.currency || 'COP')}</b></div></div>${tickets.length ? `<h3>Tickets, coupons & seats</h3>${tickets.map(ticket => `<div class="ticket"><b>Ticket ${esc(ticket.number || ticket.id)}</b> · ${esc(ticket.passenger?.given_name || '')} ${esc(ticket.passenger?.surname || '')}<br>Seat: ${esc(ticket.seat || ticket.seat_number || '—')} · State: ${esc(ticket.state || '—')} · Coupons: ${esc((ticket.coupons || []).map(c => `${c.flight_leg_instance_id || '—'} (${c.state || '—'})`).join(', ') || '—')}</div>`).join('')}` : '<p class="flight-meta">No tickets were issued (payment declined or pending).</p>'}`; }
  async function lookup(event) { event.preventDefault(); const form = event.target; if (state.busy) return; setBusy(form, true, 'Looking up…'); notice('Retrieving reservation…'); const values = new FormData(form); state.demoContext = null; try { const r = reservationOf(await request(`/reservations/${encodeURIComponent(values.get('locator'))}?surname=${encodeURIComponent(values.get('surname'))}`)); if (r.id) r.tickets = await request(`/reservations/${encodeURIComponent(r.id)}/tickets`); renderLookup(r); notice('Reservation found.', 'success'); step('manage'); } catch (error) { report(error); } finally { setBusy(form, false); } }
  function renderLookup(r) { const id = r.id, canCancel = ['CONFIRMED','PENDING_PAYMENT'].includes(r.state || r.status); const details = (r.tickets || []).map(ticket => `<div class="ticket"><b>${esc(ticket.passenger?.given_name || '')} ${esc(ticket.passenger?.surname || '')}</b> · Ticket ${esc(ticket.number || ticket.id || '—')} · Seat ${esc(ticket.seat || ticket.seat_number || ticket.coupons?.[0]?.seat || '—')} · ${esc(ticket.state || '—')}<br>Coupons: ${esc((ticket.coupons || []).map(c => `${c.flight_leg_instance_id || '—'} (${c.state || '—'})`).join(', ') || '—')}</div>`).join(''); const segments = (r.segments || r.items || []).map(s => `<div class="flight-meta">${segment(s)} · ${esc(s.departure_local || s.departure_at || '—')} → ${esc(s.arrival_local || s.arrival_at || '—')} · Price ${esc(s.price ?? s.total ?? '—')}</div>`).join(''); const payments = (r.payments || []).map(p => `${esc(p.state)} ${esc(p.amount ?? '')}`).join(', ') || '—'; $('#booking-detail').innerHTML = `<div class="detail-grid"><div>Reference<b>${esc(r.locator || id)}</b></div><div>Status<b>${esc(r.state || r.status)}</b></div><div>Total<b>${esc(r.total ?? '—')} ${esc(r.currency || 'COP')}</b></div><div>Payment<b>${payments}</b></div><div>Expires<b>${esc(r.expires_at || '—')}</b></div><div>Released<b>${esc(r.released_at || '—')}</b></div></div>${segments ? `<h3>Itinerary</h3>${segments}` : ''}<h3>Passengers, seats & tickets</h3>${details || (r.passengers || []).map(p => `<div class="ticket">${esc(p.given_name)} ${esc(p.surname)} · seat ${esc(p.seat || p.seat_number || '—')}</div>`).join('') || '<p class="flight-meta">No ticket details were returned.</p>'}${canCancel ? '<button class="secondary" id="cancel-booking" type="button">Cancel entire booking</button>' : ''}`; if (canCancel) $('#cancel-booking').onclick = () => cancel(id); }
  async function cancel(id) { if (!window.confirm('Cancel the entire reservation?')) return; notice('Cancelling reservation…'); try { renderLookup(reservationOf(await request(`/reservations/${encodeURIComponent(id)}/cancel`, { method:'POST' }))); notice('Reservation cancelled and inventory released.', 'success'); } catch (error) { report(error); } }
  $('#search-form').onsubmit = search; $('#booking-form').onsubmit = createBooking; $('#payment-form').onsubmit = pay; $('#lookup-form').onsubmit = lookup; $('#new-search').onclick = () => { show('search-panel'); step('search'); notice(''); }; $('#back-results').onclick = () => { show('results'); step('search'); }; document.querySelectorAll('[name="channel"]').forEach(input => input.onchange = () => { const agency = $('#agency-fields'); agency.hidden = input.value !== 'AGENCY'; agency.querySelectorAll('input').forEach(field => { field.required = input.value === 'AGENCY'; }); }); $('[name="date"]').min = new Date().toISOString().slice(0, 10); $('[name="operation_ref"]').value = `web-${Date.now()}`;
  if (location.protocol === 'file:') notice('Serve this folder over HTTP so it can reach the API.', 'error');
  window.Skyline = { arr: unpack, payload, request, renderFlights, renderHold, startCountdown, stopCountdown, setBusy };
})();
