// Dependency-free DOM/contract checks: node frontend/test.js
const assert = require('node:assert/strict');
const fs = require('node:fs');
const html = fs.readFileSync(__dirname + '/index.html', 'utf8');
const source = fs.readFileSync(__dirname + '/app.js', 'utf8');
const logic = require('./client-logic.js');
for (const route of ['/flights/search?', '/reservations', '/payments', '/cancel', '/tickets']) assert(source.includes(route), `missing route ${route}`);
assert(source.includes('Idempotency-Key'), 'reservation must be idempotent');
assert(source.includes('disabled = busy'), 'submit controls must lock while loading');
assert(source.includes('correlationId'), 'structured correlation errors must be surfaced');
assert(!source.includes('document_number') && !html.includes('document_number'), 'documents are not persisted and must not be requested');
assert(!html.includes('buyer_email') && !html.includes('buyer_phone'), 'non-persisted buyer fields must not be requested');
assert(html.includes('Content-Security-Policy'), 'basic CSP metadata is required');
assert(html.includes('id="search-form"') && html.includes('id="booking-form"') && html.includes('id="payment-form"') && html.includes('id="lookup-form"'), 'complete form flow');
const envelopes = [{items:[1,2]}, {results:[1]}, {itineraries:[3]}, {data:[4]}];
const unpack = x => Array.isArray(x) ? x : x.items || x.results || x.itineraries || x.data || [];
assert.deepEqual(envelopes.map(unpack), [[1,2],[1],[3],[4]]);
assert(source.includes("channel === 'AGENCY'"), 'agency channel contract');
assert(source.includes('logic.buildPayload') && source.includes('logic.countdownText'), 'runtime uses shared pure helpers');
assert(source.includes("'X-Demo-Role'] = state.demoContext.role") && source.includes("'X-Demo-Agency-Id': context.agencyId"), 'demo identity is retained across requests');
assert(source.includes("role:'AGENCY_AGENT'") && source.includes("agent-7") && source.includes("agency-1"), 'canonical agency demo identity');
assert(source.includes('payButton.disabled = true'), 'expired hold disables payment');
assert(html.includes('value="agency-1"') && html.includes('value="agent-7"'), 'seeded agency demo is ready to use');
assert(source.includes('payButton.disabled = false'), 'a new valid hold re-enables payment');
const values = new Map([['passengers[0].given_name', 'Ada'], ['passengers[0].surname', 'Lovelace'], ['channel', 'AGENCY'], ['agency_id', 'agency-1'], ['agent_id', 'agent-1']]);
values.has = values.has.bind(values); values.get = values.get.bind(values);
assert.deepEqual(logic.buildPayload({ legs: [{ id: 'leg-1' }] }, 'ECONOMY', values), { leg_ids:['leg-1'], cabin:'ECONOMY', passengers:[{ given_name:'Ada', surname:'Lovelace' }], channel:'AGENCY', agency_id:'agency-1', agent_id:'agent-1' });
assert.equal(logic.countdownText(65), 'Time remaining: 1:05');
assert.match(logic.countdownText(0), /expired/);
assert(source.includes('if (state.busy) return'), 'double submit guard is executable in handlers');
assert(source.includes('departure_local') && source.includes('arrival_local') && source.includes('timezone'), 'local schedule rendering');
assert(source.includes('released_at') && source.includes('r.payments') && source.includes('r.segments'), 'full reservation rendering');
assert.match(`${logic.countdownText(65)} America/Bogota`, /America\/Bogota/);
console.log('frontend contract/DOM tests: 24 passed');
