"""Create the in-database analytical model in the ``analytics`` schema.

The schema is deliberately separate from the OLTP ``public`` schema, while
remaining in the same PostgreSQL instance.  Facts contain source identifiers
but no passenger names or other PII.  ETL control tables are included so a
future Glue job can be rerun safely and report reconciliation metrics.
"""

from alembic import op

revision = "0006_analytics_schema"
down_revision = "0005_demo_identities"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE SCHEMA IF NOT EXISTS analytics;

        CREATE TABLE IF NOT EXISTS analytics.dim_date (
            date_key integer PRIMARY KEY,
            calendar_date date NOT NULL UNIQUE,
            year smallint NOT NULL CHECK (year BETWEEN 2000 AND 2100),
            quarter smallint NOT NULL CHECK (quarter BETWEEN 1 AND 4),
            month smallint NOT NULL CHECK (month BETWEEN 1 AND 12),
            week_of_year smallint NOT NULL CHECK (week_of_year BETWEEN 1 AND 53),
            day_of_month smallint NOT NULL CHECK (day_of_month BETWEEN 1 AND 31),
            day_of_week smallint NOT NULL CHECK (day_of_week BETWEEN 1 AND 7)
        );

        CREATE TABLE IF NOT EXISTS analytics.dim_route (
            route_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_route_id uuid NOT NULL UNIQUE,
            route_code varchar(64) NOT NULL UNIQUE,
            origin varchar(3) NOT NULL,
            destination varchar(3) NOT NULL,
            CONSTRAINT dim_route_distinct_airports CHECK (origin <> destination)
        );

        CREATE TABLE IF NOT EXISTS analytics.dim_flight (
            flight_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_flight_instance_id uuid NOT NULL UNIQUE,
            source_scheduled_flight_id uuid,
            flight_number varchar(10) NOT NULL,
            service_date date NOT NULL,
            flight_state varchar(16) NOT NULL
        );

        CREATE TABLE IF NOT EXISTS analytics.dim_cabin (
            cabin_key smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cabin_code varchar(16) NOT NULL UNIQUE,
            display_name varchar(40) NOT NULL
        );

        CREATE TABLE IF NOT EXISTS analytics.dim_fare_band (
            fare_band_key smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fare_band_code varchar(40) NOT NULL UNIQUE,
            min_days_before_departure integer,
            max_days_before_departure integer,
            CONSTRAINT fare_band_day_bounds CHECK (
                min_days_before_departure IS NULL OR min_days_before_departure >= 0
            ),
            CONSTRAINT fare_band_day_order CHECK (
                min_days_before_departure IS NULL OR max_days_before_departure IS NULL
                OR min_days_before_departure <= max_days_before_departure
            )
        );

        CREATE TABLE IF NOT EXISTS analytics.dim_channel (
            channel_key smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            channel_code varchar(16) NOT NULL UNIQUE
        );

        CREATE TABLE IF NOT EXISTS analytics.dim_agency (
            agency_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_agency_id varchar(100) UNIQUE,
            agency_name varchar(120) NOT NULL,
            active boolean NOT NULL DEFAULT true
        );

        -- Grain: one reservation item (one passenger and one operational leg).
        CREATE TABLE IF NOT EXISTS analytics.fact_sales_segment (
            sales_segment_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_reservation_item_id uuid NOT NULL UNIQUE,
            source_reservation_id uuid NOT NULL,
            booking_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
            departure_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
            route_key bigint NOT NULL REFERENCES analytics.dim_route(route_key),
            flight_key bigint NOT NULL REFERENCES analytics.dim_flight(flight_key),
            cabin_key smallint NOT NULL REFERENCES analytics.dim_cabin(cabin_key),
            fare_band_key smallint NOT NULL REFERENCES analytics.dim_fare_band(fare_band_key),
            channel_key smallint NOT NULL REFERENCES analytics.dim_channel(channel_key),
            agency_key bigint REFERENCES analytics.dim_agency(agency_key),
            reservation_state varchar(24) NOT NULL,
            resource_state varchar(16) NOT NULL,
            passenger_quantity smallint NOT NULL DEFAULT 1 CHECK (passenger_quantity > 0),
            base_fare numeric(14,2) NOT NULL CHECK (base_fare >= 0),
            airport_fee numeric(14,2) NOT NULL CHECK (airport_fee >= 0),
            tax numeric(14,2) NOT NULL CHECK (tax >= 0),
            gross_amount numeric(14,2) NOT NULL CHECK (gross_amount >= 0),
            approved_revenue numeric(14,2) NOT NULL DEFAULT 0 CHECK (approved_revenue >= 0),
            refund_amount numeric(14,2) NOT NULL DEFAULT 0 CHECK (refund_amount >= 0),
            net_revenue numeric(14,2) GENERATED ALWAYS AS (approved_revenue - refund_amount) STORED,
            advance_days integer NOT NULL CHECK (advance_days >= 0),
            commission_amount numeric(14,2) NOT NULL DEFAULT 0 CHECK (commission_amount >= 0),
            currency char(3) NOT NULL DEFAULT 'COP',
            source_updated_at timestamptz NOT NULL,
            CHECK (refund_amount <= approved_revenue),
            loaded_at timestamptz NOT NULL DEFAULT now()
        );

        -- Grain: one reservation, preventing multi-leg reservations from being counted twice.
        CREATE TABLE IF NOT EXISTS analytics.fact_reservation (
            reservation_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_reservation_id uuid NOT NULL UNIQUE,
            created_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
            departure_date_key integer REFERENCES analytics.dim_date(date_key),
            cancellation_date_key integer REFERENCES analytics.dim_date(date_key),
            channel_key smallint NOT NULL REFERENCES analytics.dim_channel(channel_key),
            agency_key bigint REFERENCES analytics.dim_agency(agency_key),
            reservation_state varchar(24) NOT NULL,
            total_amount numeric(14,2) NOT NULL CHECK (total_amount >= 0),
            commission_amount numeric(14,2) NOT NULL CHECK (commission_amount >= 0),
            cancellation_flag boolean NOT NULL DEFAULT false,
            previously_confirmed boolean NOT NULL DEFAULT false,
            advance_days integer CHECK (advance_days IS NULL OR advance_days >= 0),
            cancellation_at timestamptz,
            source_updated_at timestamptz NOT NULL,
            loaded_at timestamptz NOT NULL DEFAULT now()
        );

        -- Grain: one inventory row per flight-leg/cabin at each ETL snapshot.
        CREATE TABLE IF NOT EXISTS analytics.fact_leg_occupancy (
            occupancy_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_inventory_id uuid NOT NULL,
            snapshot_at timestamptz NOT NULL,
            departure_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
            route_key bigint NOT NULL REFERENCES analytics.dim_route(route_key),
            flight_key bigint NOT NULL REFERENCES analytics.dim_flight(flight_key),
            cabin_key smallint NOT NULL REFERENCES analytics.dim_cabin(cabin_key),
            capacity integer NOT NULL CHECK (capacity >= 0),
            held integer NOT NULL CHECK (held >= 0),
            confirmed integer NOT NULL CHECK (confirmed >= 0),
            available integer GENERATED ALWAYS AS (capacity - held - confirmed) STORED,
            occupancy_ratio numeric(8,5) GENERATED ALWAYS AS (
                CASE WHEN capacity > 0 THEN confirmed::numeric / capacity ELSE 0 END
            ) STORED,
            loaded_at timestamptz NOT NULL DEFAULT now(),
            UNIQUE (source_inventory_id, snapshot_at),
            CHECK (capacity >= held + confirmed)
        );

        CREATE TABLE IF NOT EXISTS analytics.bridge_reservation_route (
            reservation_key bigint NOT NULL REFERENCES analytics.fact_reservation(reservation_key) ON DELETE CASCADE,
            route_key bigint NOT NULL REFERENCES analytics.dim_route(route_key),
            departure_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
            route_sequence smallint NOT NULL CHECK (route_sequence > 0),
            PRIMARY KEY (reservation_key, route_key),
            UNIQUE (reservation_key, route_sequence)
        );

        CREATE TABLE IF NOT EXISTS analytics.etl_run (
            run_id uuid PRIMARY KEY,
            pipeline_name varchar(100) NOT NULL,
            started_at timestamptz NOT NULL DEFAULT now(),
            finished_at timestamptz,
            source_cutoff_at timestamptz,
            status varchar(16) NOT NULL CHECK (status IN ('RUNNING','SUCCEEDED','FAILED')),
            rows_extracted integer NOT NULL DEFAULT 0 CHECK (rows_extracted >= 0),
            rows_loaded integer NOT NULL DEFAULT 0 CHECK (rows_loaded >= 0),
            reconciliation jsonb NOT NULL DEFAULT '{}'::jsonb,
            error_message text
        );

        CREATE TABLE IF NOT EXISTS analytics.etl_watermark (
            pipeline_name varchar(100) PRIMARY KEY,
            source_name varchar(100) NOT NULL,
            last_successful_cutoff_at timestamptz,
            last_run_id uuid REFERENCES analytics.etl_run(run_id),
            updated_at timestamptz NOT NULL DEFAULT now()
        );

        CREATE INDEX IF NOT EXISTS ix_fact_sales_date_route
            ON analytics.fact_sales_segment(departure_date_key, route_key);
        CREATE INDEX IF NOT EXISTS ix_fact_sales_fare
            ON analytics.fact_sales_segment(fare_band_key, departure_date_key);
        CREATE INDEX IF NOT EXISTS ix_fact_reservation_state_date
            ON analytics.fact_reservation(reservation_state, created_date_key);
        CREATE INDEX IF NOT EXISTS ix_fact_occupancy_route_snapshot
            ON analytics.fact_leg_occupancy(route_key, snapshot_at);
        CREATE INDEX IF NOT EXISTS ix_bridge_reservation_route_route_date
            ON analytics.bridge_reservation_route(route_key, departure_date_key);
        CREATE INDEX IF NOT EXISTS ix_etl_run_pipeline_started
            ON analytics.etl_run(pipeline_name, started_at DESC);
        """
    )


def downgrade() -> None:
    # The schema is owned entirely by this revision; no public/OLTP objects are touched.
    op.execute("DROP SCHEMA IF EXISTS analytics CASCADE")
